#!/bin/bash
# _grade-all.sh — run grade.sh on all 8 audits, emit aggregated report.
set -u
GRADER="/mnt/c/Users/koosh/phenotype-registry/registry/audit-absorption-justification/grade.sh"
AUDITS_DIR="/mnt/c/Users/koosh/phenotype-registry/audits/absorption-justifications"
cd "$AUDITS_DIR" || exit 1

python3 <<'PYEOF'
import json, os, subprocess, glob

GRADER = "/mnt/c/Users/koosh/phenotype-registry/registry/audit-absorption-justification/grade.sh"
AUDITS_DIR = "/mnt/c/Users/koosh/phenotype-registry/audits/absorption-justifications"

results = []
for f in sorted(glob.glob(os.path.join(AUDITS_DIR, "*-2026-06-23.md"))):
    name = os.path.basename(f)
    p = subprocess.run(["bash", GRADER, f], capture_output=True, text=True)
    try:
        d = json.loads(p.stdout)
    except json.JSONDecodeError as e:
        print(f"  {name}: JSON parse error: {e}")
        continue
    pillars = {p["id"]: p for p in d["pillars"]}
    p6 = pillars[6]
    p7 = pillars[7]
    p4 = pillars[4]
    print(f"  {name:<32}  {int(d['score']):>2}/14  {d['percentage']:>6}%  {d['grade']}  P4={p4['status']:<8} P6={p6['status']:<8} P7={p7['status']}")
    results.append({"name": name, "score": d["score"], "pct": float(d["percentage"]), "grade": d["grade"], "pillars": {p["id"]: p["status"] for p in d["pillars"]}})

print()
print("Fleet summary:")
print("==============")
total = sum(r["score"] for r in results)
n = len(results)
avg = total / n if n else 0
print(f"  Audits graded:    {n}")
print(f"  Total score:      {total:.1f} / {n*14}")
print(f"  Fleet average:    {avg:.2f}/14  ({100*avg/14:.2f}%)")
g_dist = {}
for r in results:
    g_dist[r["grade"]] = g_dist.get(r["grade"], 0) + 1
print(f"  Grade distribution: {g_dist}")

# Write machine-readable GRADES.json next to the audits.
grades_path = os.path.join(AUDITS_DIR, "GRADES.json")
with open(grades_path, "w") as f:
    json.dump({
        "fleet_average_score": round(avg, 3),
        "fleet_average_percentage": round(100*avg/14, 2),
        "fleet_grade_distribution": g_dist,
        "pillar_weights": {"P1": 3, "P2": 3, "P3": 2, "P4": 2, "P5": 1, "P6": 2, "P7": 1},
        "grading_rubric": "registry/audit-absorption-justification/schema.json",
        "grading_engine": "registry/audit-absorption-justification/grade.sh",
        "audits": [
            {
                "name": r["name"],
                "score": r["score"],
                "percentage": r["pct"],
                "grade": r["grade"],
                "pillar_status": r["pillars"],
            } for r in results
        ],
    }, f, indent=2)
print(f"\nWrote {grades_path}")

# Write human-readable GRADES.md.
md_path = os.path.join(AUDITS_DIR, "GRADES.md")
with open(md_path, "w") as f:
    f.write(f"# Absorption-Justification Grading Report\n\n")
    f.write(f"Fleet average: **{avg:.2f}/14** ({100*avg/14:.2f}%)  ·  Grade distribution: {g_dist}\n\n")
    f.write(f"Pillar weights: P1=3, P2=3, P3=2, P4=2, P5=1, P6=2, P7=1 (total 14)\n\n")
    f.write("| Audit | Score | Pct | Grade | P1 | P2 | P3 | P4 | P5 | P6 | P7 |\n")
    f.write("|---|---:|---:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|\n")
    for r in sorted(results, key=lambda x: -x["score"]):
        ps = r["pillars"]
        f.write(f"| {r['name']} | {r['score']}/14 | {r['pct']:.2f}% | {r['grade']} | {ps.get(1,'-')} | {ps.get(2,'-')} | {ps.get(3,'-')} | {ps.get(4,'-')} | {ps.get(5,'-')} | {ps.get(6,'-')} | {ps.get(7,'-')} |\n")
    f.write(f"\n*Generated by `_grade-all.sh` on 2026-06-23 — P7 closeout pass.*\n")
print(f"Wrote {md_path}")
PYEOF
