# SonarCloud automatic analysis scope (see docs: .sonarcloud.properties on analyzed branch).
sonar.exclusions=audits/phenotype-org-audits/**,imports/**
sonar.cpd.exclusions=audits/phenotype-org-audits/**,imports/**
