version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
    assignees:
      - KooshaPari
    open-pull-requests-limit: 10
