#!/usr/bin/env python3
"""regen-ecosystem-map.py — auto-regenerate ECOSYSTEM_MAP.md from SSOT inputs.

This script is the CI-gated regenerator for ``ECOSYSTEM_MAP.md`` (the
canonical live ecosystem index for the KooshaPari/phenotype-registry repo).

SSOT inputs (read in this order):

  1. ``SPEC.md``                              — the Registry Index table.
  2. ``docs/registries.md``                   — the Archive Migration Redirects
                                                table.
  3. ``phenotype-registry-curation-data/_bindings.json``
                                              — the bound repo set (keys are
                                                repo slugs; values carry
                                                per-channel prompt counts).

The script is deterministic: same inputs → same output. It does NOT call the
network. It does NOT touch the cluster-specific hand-curated tables in the
existing ECOSYSTEM_MAP.md; those remain as the human-edited appendix
``## 3. Hand-curated cluster tables (preserved verbatim)`` which the script
re-attaches from the existing file (or, if no existing file exists, the
appendix is empty).

Usage
-----
    # Regenerate in place (overwrites ECOSYSTEM_MAP.md):
    python3 scripts/regen-ecosystem-map.py

    # Write to a different file (does not touch the canonical one):
    python3 scripts/regen-ecosystem-map.py --out /tmp/ECOSYSTEM_MAP.new.md

    # CI gate: exit 1 if the on-disk file is stale (would change):
    python3 scripts/regen-ecosystem-map.py --check

    # Show what would change (no write, no non-zero exit):
    python3 scripts/regen-ecosystem-map.py --diff

    # Override the path to the sibling curation-data repo:
    python3 scripts/regen-ecosystem-map.py --bindings /path/to/_bindings.json

Exit codes
----------
    0  — file is up to date (or --check passed) or wrote successfully
    1  — --check detected drift; file would change
    2  — I/O / parse error (missing input, malformed JSON, etc.)
    3  — usage error (bad flag combination)

Drift detection markers
-----------------------
The script always appends an HTML comment block at the end of the rendered
file, of the form::

    <!-- drift-detection: ... -->

These markers are read by the validator in ``--check`` mode to confirm
that the file was generated by this script. If they are missing or have
been hand-edited away, ``--check`` exits 1.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

# --- repo layout -----------------------------------------------------------

REPO_ROOT_DEFAULT = Path(__file__).resolve().parent.parent
SPEC_PATH = REPO_ROOT_DEFAULT / "SPEC.md"
REGISTRIES_DOC = REPO_ROOT_DEFAULT / "docs" / "registries.md"
ECOSYSTEM_MAP = REPO_ROOT_DEFAULT / "ECOSYSTEM_MAP.md"

# Sibling repo: the registry repo's curation-data half.
# We default to ``../phenotype-registry-curation-data`` which is the layout
# when both repos are co-located under the same monorepo parent.
BINDINGS_DEFAULT = (
    REPO_ROOT_DEFAULT.parent / "phenotype-registry-curation-data" / "_bindings.json"
)

# --- drift markers ---------------------------------------------------------

DRIFT_MARKER_AUTO_REGEN = (
    "<!-- drift-detection: auto-regen-on-push-pr "
    "(.github/workflows/ecosystem-map-regen.yml) -->"
)
DRIFT_MARKER_WEEKLY = (
    "<!-- drift-detection: weekly-cron "
    "(.github/workflows/ecosystem-map-weekly.yml) -->"
)
DRIFT_MARKER_SCRIPT = (
    "<!-- drift-detection: regen-script scripts/regen-ecosystem-map.py -->"
)
DRIFT_MARKER_GENERATED_AT = (
    "<!-- drift-detection: generated-at "  # value appended at render time
)
DRIFT_BLOCK = "\n".join(
    [
        "",
        DRIFT_MARKER_AUTO_REGEN,
        DRIFT_MARKER_WEEKLY,
        DRIFT_MARKER_SCRIPT,
    ]
)


# --- error helpers ---------------------------------------------------------


def die(msg: str, code: int = 2) -> "NoReturn":  # type: ignore[name-defined]
    """Print ``msg`` to stderr and exit with ``code``."""
    print(f"regen-ecosystem-map: {msg}", file=sys.stderr)
    sys.exit(code)


# --- SPEC.md parsing -------------------------------------------------------


def parse_spec_registries(spec_text: str) -> list[dict[str, str]]:
    """Extract the ``## Registry Index`` table from ``SPEC.md``.

    The table has columns: Registry | URL | Purpose | Key Files
    """
    # find the registry index section
    section_re = re.compile(
        r"^##\s+Registry Index\s*$\n(.*?)(?=^##\s|\Z)", re.MULTILINE | re.DOTALL
    )
    section = section_re.search(spec_text)
    if not section:
        return []
    body = section.group(1)
    # only look at lines that look like table rows (start with ``|``, not
    # the separator row ``|---|``, not blank).
    rows: list[dict[str, str]] = []
    for line in body.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        if re.match(r"^\|[\s\-:|]+\|", line):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 4:
            continue
        # The URL cell may carry markdown link ``[text](url)`` — preserve raw.
        rows.append(
            {
                "name": cells[0],
                "url": cells[1],
                "purpose": cells[2],
                "key_files": cells[3],
            }
        )
    return rows


# --- docs/registries.md parsing -------------------------------------------


_ARCHIVE_TABLE_HEADER = re.compile(
    r"^##\s+Archive Migration Redirects\b", re.MULTILINE
)
_TABLE_SEP = re.compile(r"^\|[\s\-:|]+\|$")


def _extract_first_md_table_after(
    text: str, header_re: re.Pattern[str]
) -> list[list[str]]:
    """Return the first markdown pipe-table that follows ``header_re``."""
    m = header_re.search(text)
    if not m:
        return []
    rest = text[m.end():]
    rows: list[list[str]] = []
    started = False
    for line in rest.splitlines():
        if not line.startswith("|"):
            if started:
                # end of the contiguous table block
                if rows:
                    break
                continue
            continue
        if _TABLE_SEP.match(line):
            started = True
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        rows.append(cells)
        started = True
    return rows


def parse_archive_redirects(registries_text: str) -> list[dict[str, str]]:
    """Extract the ``## Archive Migration Redirects`` table from
    ``docs/registries.md`` (retired source | canonical owner).
    """
    rows = _extract_first_md_table_after(registries_text, _ARCHIVE_TABLE_HEADER)
    out: list[dict[str, str]] = []
    for r in rows:
        if len(r) < 2:
            continue
        out.append({"source": r[0], "owner": r[1]})
    return out


# --- _bindings.json parsing -----------------------------------------------


def load_bindings(path: Path) -> dict[str, dict]:
    """Load the bound-set JSON and return a dict keyed by repo slug.

    A repo is *bound* iff it has at least one of ``plan``, ``prompt``,
    or ``response`` channels present and non-empty. We still keep the
    full key set in the returned dict so callers can compute coverage.
    """
    if not path.exists():
        die(f"bindings file not found: {path}")
    try:
        with path.open() as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        die(f"could not parse {path}: {e}")
    if not isinstance(data, dict):
        die(f"unexpected shape in {path}: expected object at root, got {type(data).__name__}")
    return data


def bound_repo_set(bindings: dict[str, dict]) -> set[str]:
    """Return the set of repo slugs that have at least one non-empty channel."""
    out: set[str] = set()
    for slug, channels in bindings.items():
        if not isinstance(channels, dict):
            continue
        if any(
            isinstance(channels.get(k), list) and len(channels.get(k)) > 0
            for k in ("plan", "prompt", "response")
        ):
            out.add(slug)
    return out


# --- existing-file appendix extraction -----------------------------------


def extract_hand_curated_appendix(existing: str) -> str:
    """Return the hand-curated cluster appendix from the existing file.

    The appendix is the text from the first ``## 3.`` (Duplication Clusters)
    section up to but not including the trailing ``## 9. Changelog`` or the
    ``drift-detection`` comment block. If no such marker exists, returns "".
    """
    # The first thing we want to preserve is everything from the first
    # ``## 3.`` heading up to the changelog (``## 9.``) OR the drift markers.
    m3 = re.search(r"^##\s+3\.\s+", existing, re.MULTILINE)
    if not m3:
        return ""
    start = m3.start()
    # The end is the latest of: changelog start, drift-detection start.
    end_candidates: list[int] = []
    m9 = re.search(r"^##\s+9\.\s+", existing, re.MULTILINE)
    if m9:
        end_candidates.append(m9.start())
    md = re.search(r"^<!--\s+drift-detection:", existing, re.MULTILINE)
    if md:
        end_candidates.append(md.start())
    end = min(end_candidates) if end_candidates else len(existing)
    return existing[start:end].rstrip() + "\n"


# --- render ---------------------------------------------------------------


def _md_table(headers: list[str], rows: Iterable[Iterable[str]]) -> str:
    headers = list(headers)
    lines = ["| " + " | ".join(headers) + " |"]
    lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
    for row in rows:
        lines.append("| " + " | ".join(str(c) for c in row) + " |")
    return "\n".join(lines)


def render(
    *,
    spec_registries: list[dict[str, str]],
    archive_redirects: list[dict[str, str]],
    bound: set[str],
    bound_total: int,
    bindings_path: Path,
    existing_appendix: str,
    now: datetime,
) -> str:
    """Render the full ``ECOSYSTEM_MAP.md`` body.

    The output is a deterministic concatenation of:

        header
        §1  Canonical Registries (from SPEC.md)
        §2  Bound Repo Set    (from _bindings.json)
        §3  Hand-curated appendix (preserved from prior file, if any)
        §4  Archive Migration Redirects (from docs/registries.md)
        drift-detection comment block
    """
    iso = now.strftime("%Y-%m-%dT%H:%M:%SZ")
    date_only = now.strftime("%Y-%m-%d")
    bound_count = len(bound)

    parts: list[str] = []
    parts.append(
        f"""# KooshaPari Ecosystem Map

> **Auto-regenerated.** Do not hand-edit the auto sections. See the
> drift-detection comment block at the bottom for the regen script + CI gates.
> Generated: {iso} | Bound repos: {bound_count} of {bound_total} keys in
> `{bindings_path.name}` | Validator: `scripts/regen-ecosystem-map.py --check`

---

## Index Authority & Staleness

This file (`ECOSYSTEM_MAP.md`) is the **canonical live ecosystem index** — the
authoritative answer to *what repos exist and how they connect*. When another
index disagrees with this one about repo roles or dependencies, this file wins.

| Repo | Role |
|------|------|
| **phenotype-registry** (this repo) | **INDEX** — canonical ecosystem map + dependency graph |
| **PhenoSpecs** | ADRs, API contracts, specs |
| **PhenoHandbook** | conventions / patterns |
| **AgilePlus** | spec-driven dev substrate (per SPEC.md § References) |

**Regeneration:** this file is regenerated by
`scripts/regen-ecosystem-map.py` on every push / pull request to `main`
(`.github/workflows/ecosystem-map-regen.yml`) and weekly by the cron workflow
`.github/workflows/ecosystem-map-weekly.yml`, which opens a remediation PR on
drift via `peter-evans/create-pull-request@v6`.

---

## 1. Canonical Registries (from SPEC.md)

The canonical registries declared in `SPEC.md` § Registry Index:
"""
    )

    if spec_registries:
        parts.append(
            _md_table(
                ["Registry", "URL", "Purpose", "Key Files"],
                [(r["name"], r["url"], r["purpose"], r["key_files"]) for r in spec_registries],
            )
        )
    else:
        parts.append(
            "_(No Registry Index table found in SPEC.md — please add one.)_"
        )
    parts.append("")

    # --- §2: Bound repo set -----------------------------------------------
    parts.append(
        f"""## 2. Bound Repo Set (from `{bindings_path.name}`)

`_bindings.json` is the per-channel binding ledger produced by
`phenotype-registry-curation-data`. A repo is **bound** iff it has at
least one non-empty channel (`plan` / `prompt` / `response`).

Summary: **{bound_count}** bound repos of **{bound_total}** total keys
({bound_count}/{bound_total}, {(bound_count / bound_total * 100) if bound_total else 0:.1f}% coverage).
"""
    )

    if bound:
        sorted_bound = sorted(bound)
        # Render as a 3-column table (repo, index, in-set) for readability.
        # The index is the position in the alphabetised list.
        rows = [(slug, str(i + 1), "✓") for i, slug in enumerate(sorted_bound)]
        parts.append(
            _md_table(["Repo", "#", "Bound?"], rows)
        )
    else:
        parts.append("_(No bound repos found in `_bindings.json`.)_")
    parts.append("")

    # --- appendix ---------------------------------------------------------
    if existing_appendix.strip():
        parts.append(
            f"""## 3. Hand-curated Appendix (preserved verbatim from prior file)

The following cluster-specific tables and the dependency graph are
hand-curated and preserved verbatim by the regen script. They are
NOT regenerated; the script only ensures the auto sections above stay
fresh. To regenerate, run `task regen-ecosystem-map` and review the diff.

"""
        )
        parts.append(existing_appendix.rstrip())
        parts.append("")

    # --- §4: Archive redirects -------------------------------------------
    parts.append(
        f"""## 4. Archive Migration Redirects (from docs/registries.md)

Deleted or absorbed source repos retain history in `projects/*.json` with
`absorbed_into` and `absorption_note`. Resolve capabilities at the canonical
owner. The table below is extracted from `docs/registries.md` and is the
machine-checked source for the "Absorption outcomes" section in the
hand-curated appendix.
"""
    )
    if archive_redirects:
        parts.append(
            _md_table(
                ["Retired source", "Canonical owner"],
                [(r["source"], r["owner"]) for r in archive_redirects],
            )
        )
    else:
        parts.append(
            "_(No Archive Migration Redirects table found in docs/registries.md.)_"
        )
    parts.append("")

    # --- drift markers ----------------------------------------------------
    parts.append("---")
    parts.append("")
    parts.append("## Drift detection")
    parts.append("")
    parts.append(
        "This file is auto-regenerated. Drift is detected by the comment block below."
    )
    parts.append("")
    parts.append(DRIFT_MARKER_AUTO_REGEN)
    parts.append(DRIFT_MARKER_WEEKLY)
    parts.append(DRIFT_MARKER_SCRIPT)
    parts.append(f"{DRIFT_MARKER_GENERATED_AT}{iso} -->")
    parts.append("")

    return "\n".join(parts)


# --- main ------------------------------------------------------------------


def main() -> int:
    p = argparse.ArgumentParser(
        prog="regen-ecosystem-map.py",
        description="Regenerate ECOSYSTEM_MAP.md from SPEC.md, docs/registries.md, "
        "and _bindings.json. Use --check as a CI gate.",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the on-disk file is stale (would change); do not write.",
    )
    p.add_argument(
        "--diff",
        action="store_true",
        help="Print a unified diff of the would-be change; do not write, "
        "do not exit non-zero.",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write the rendered file to this path instead of ECOSYSTEM_MAP.md. "
        "Implies the file is allowed to differ from the on-disk one (no gate).",
    )
    p.add_argument(
        "--bindings",
        type=Path,
        default=BINDINGS_DEFAULT,
        help=f"Path to the _bindings.json file (default: {BINDINGS_DEFAULT}).",
    )
    p.add_argument(
        "--spec",
        type=Path,
        default=SPEC_PATH,
        help=f"Path to SPEC.md (default: {SPEC_PATH}).",
    )
    p.add_argument(
        "--registries-doc",
        type=Path,
        default=REGISTRIES_DOC,
        help=f"Path to docs/registries.md (default: {REGISTRIES_DOC}).",
    )
    args = p.parse_args()

    if args.check and args.out is not None:
        die("--check cannot be combined with --out", code=3)
    if args.check and args.diff:
        die("--check cannot be combined with --diff", code=3)

    # --- load inputs ------------------------------------------------------
    if not args.spec.exists():
        die(f"SPEC.md not found at {args.spec}")
    if not args.registries_doc.exists():
        die(f"docs/registries.md not found at {args.registries_doc}")
    spec_text = args.spec.read_text()
    registries_text = args.registries_doc.read_text()

    spec_registries = parse_spec_registries(spec_text)
    archive_redirects = parse_archive_redirects(registries_text)
    bindings = load_bindings(args.bindings)
    bound = bound_repo_set(bindings)

    # --- existing-file appendix -----------------------------------------
    existing = ""
    if ECOSYSTEM_MAP.exists():
        existing = ECOSYSTEM_MAP.read_text()
    appendix = extract_hand_curated_appendix(existing) if existing else ""

    # --- render ----------------------------------------------------------
    now = datetime.now(timezone.utc)
    rendered = render(
        spec_registries=spec_registries,
        archive_redirects=archive_redirects,
        bound=bound,
        bound_total=len(bindings),
        bindings_path=args.bindings,
        existing_appendix=appendix,
        now=now,
    )

    # --- emit ------------------------------------------------------------
    if args.check:
        if not ECOSYSTEM_MAP.exists():
            print(f"FAIL  ECOSYSTEM_MAP.md missing at {ECOSYSTEM_MAP}", file=sys.stderr)
            return 1
        if rendered == existing:
            print(f"PASS  ECOSYSTEM_MAP.md is up to date ({len(rendered)} bytes)")
            return 0
        # Show the first few changed lines for triage.
        print(
            f"FAIL  ECOSYSTEM_MAP.md is stale — regen would change "
            f"{len(rendered)} bytes vs on-disk {len(existing)} bytes",
            file=sys.stderr,
        )
        # Emit a small diff to stderr for the GH Actions log.
        import difflib

        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="ECOSYSTEM_MAP.md (on disk)",
            tofile="ECOSYSTEM_MAP.md (regen would write)",
            n=3,
        )
        sys.stderr.writelines(diff)
        return 1

    if args.diff:
        if not ECOSYSTEM_MAP.exists():
            print(f"(no existing file; rendered {len(rendered)} bytes)")
            print(rendered)
            return 0
        import difflib

        diff = difflib.unified_diff(
            existing.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile="ECOSYSTEM_MAP.md (on disk)",
            tofile="ECOSYSTEM_MAP.md (regen would write)",
            n=3,
        )
        sys.stdout.writelines(diff)
        return 0

    # write mode
    out_path: Path = args.out if args.out is not None else ECOSYSTEM_MAP
    out_path.write_text(rendered)
    print(f"OK    wrote {len(rendered)} bytes to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
