#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
INDEX_DIR="$DOCS_DIR/index"

mkdir -p "$INDEX_DIR" "$DOCS_DIR/.generated"

all_files=$(rg --files "$ROOT_DIR" -g "**/*.md" -g '!**/node_modules/**' -g '!**/.worktrees/**' -g '!**/default/**' | sort)

# Compute relative path from INDEX_DIR (handbook/docs/index/) to a file under ROOT_DIR.
# If the file lives under docs/ (depth >= 2 from ROOT), it is a sibling of INDEX_DIR
# so we only need ../ + the docs-subpath.  If the file is at ROOT level (depth == 1)
# we need ../../ + filename.
relpath_from_index() {
  local abs_file="$1"
  local rel="${abs_file#${ROOT_DIR}/}"
  local parent_dir
  parent_dir="$(dirname "$rel")"
  local depth
  depth="$(echo "$parent_dir" | tr -cd '/' | wc -c)"
  if [ "$depth" -ge 1 ]; then
    # File is under docs/something/ — sibling of index/
    echo "../$rel"
  else
    # File is at ROOT level — two levels up from index/
    echo "../../$rel"
  fi
}

write_bucket() {
  local title="$1"
  local out="$2"
  local pattern="$3"
  {
    echo "# $title"
    echo
    echo "Autogenerated by docs/scripts/generate-doc-index.sh"
    echo
    while IFS= read -r f; do
      rel="${f#${ROOT_DIR}/}"
      if [[ "$rel" =~ $pattern ]]; then
        echo "- [$rel]($(relpath_from_index "$f"))"
      fi
    done <<< "$all_files"
  } > "$out"
}

{
  echo '# Raw/All'
  echo
  echo 'Autogenerated by docs/scripts/generate-doc-index.sh'
  echo
  while IFS= read -r f; do
    rel="${f#${ROOT_DIR}/}"
    echo "- [$rel]($(relpath_from_index "$f"))"
  done <<< "$all_files"
} > "$INDEX_DIR/raw-all.md"

write_bucket "Planning" "$INDEX_DIR/planning.md" '(plan|roadmap|wbs|backlog|planning)'
write_bucket "Specs" "$INDEX_DIR/specs.md" '(spec|prd|adr|requirements)'
write_bucket "Research" "$INDEX_DIR/research.md" '(research|analysis|spike)'
write_bucket "Worklogs" "$INDEX_DIR/worklogs.md" '(worklog|session|report|reports)'
write_bucket "Other" "$INDEX_DIR/other.md" '.*'

printf '{\n  "generated": true,\n  "tool": "docs/scripts/generate-doc-index.sh"\n}\n' > "$DOCS_DIR/.generated/doc-index.json"
