[package]
name = "phenotype-macros"
version.workspace = true
edition.workspace = true
license = "MIT OR Apache-2.0"
repository = "https://github.com/KooshaPari/Pyron"
description = "phenotype macros — Phenotype infrastructure crate (Pyron)"
documentation = "https://docs.rs/phenotype-macros"
keywords = ["phenotype", "pyron", "macros"]
categories = ["development-tools::procedural-macro-helpers"]
authors = ["kooshapari"]

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
