name: TruffleHog Secrets Scan
permissions:
  contents: read
  pull-requests: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "17 3 * * *"
  workflow_dispatch:
jobs:
  trufflehog-pr-differential:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog PR differential scan
        uses: trufflesecurity/trufflehog@f446421baf832d6356c42c1743d99abff52ff334 # v-latest
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}

  trufflehog-history:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog full history scan
        uses: trufflesecurity/trufflehog@f446421baf832d6356c42c1743d99abff52ff334 # v-latest
        with:
          path: ./
